### ISSUE TITLE
First Issue: Your Name 

### ISSUE THREAD

**Issue by antonroesler** [antonroesler/application-landscape-visualizer#1]
To get familiar with Github, each contributor should fork the repo. Save the repo locally on your PC. Everyone should then create a new branch, e.g. with the name 'myname'. Open the Readme.md and add your name. Then push the new branch to Github and create a pull request to the original repo. This is how we will always do it in the future.

**Comment by pfrechFra** [comment]
added name #2

**Comment by antonroesler** [comment]
**#LearningByDoing**

**Comment by pfrechFra** [comment]
Done with #1
