### ISSUE TITLE
'+tag' in 'Departments' field in create node should be '+department'

### ISSUE THREAD

**Issue by antonroesler** [antonroesler/application-landscape-visualizer#100]
this should be changed to "+department", right?
![Bildschirmfoto 2021-06-11 um 14 58 12](https://user-images.githubusercontent.com/45258920/121691678-914d5880-cac7-11eb-8adc-b5b5a5662d06.png)

**Comment by leo-hsk** [comment]
Locally fixed.
Gonna be merged into main with next pull request.
