### ISSUE TITLE
Filter from histogram

### ISSUE THREAD

**Issue by leo-hsk** [antonroesler/application-landscape-visualizer#110]
Even though there is a message that there are no fnodes with this filter, there is a filter added to the filters tab which is wrong
![image](https://user-images.githubusercontent.com/52975667/122031501-0e7e1380-cdcf-11eb-9609-1bd39e484e59.png)
![image](https://user-images.githubusercontent.com/52975667/122031528-163db800-cdcf-11eb-858f-9311ef80c7eb.png)
BI filter shoudnt be there

**Comment by leo-hsk** [comment]
We need to rework this feature because there are plenty of bugs. 
Multiple fliters are then active even thoug they are not on the diagram etc...

**Comment by leo-hsk** [comment]
Is no problem anymore, if anton adds the eventlistener and updates the histogram after applying a filter.
Am I right? @antonroesler

**Comment by leo-hsk** [comment]
Another problem: Not possible to filter after start- and shutdown-year, but still uses the startDate, shutdownDate attribute. Maybe we can change that @antonroesler.

**Comment by antonroesler** [comment]
How is this coming along?

**Comment by leo-hsk** [comment]
Should be fine now, just created the pull request
