### ISSUE TITLE
We should speak of applications and connections instead of links and nodes.

### ISSUE THREAD

**Issue by leo-hsk** [antonroesler/application-landscape-visualizer#117]
We should change all the ui elements to application and connection, because these are the business terms used for our customers. Nodes and Links are the internal names for elements.

E.g. The customer does not want to create a "node". he wants to add an application to the diagram

**Comment by antonroesler** [comment]
Sounds good

**Comment by leo-hsk** [comment]
![image](https://user-images.githubusercontent.com/52975667/124356888-f274d180-dc18-11eb-8961-677c21a4dcf9.png)
E.g need to be changed
