### ISSUE TITLE
Restrict length of filter names

### ISSUE THREAD

**Issue by antonroesler** [antonroesler/application-landscape-visualizer#122]
If filter names are longer than n characters, just cut the rest. Make sure this is done right before putting the name on the html and not when reading the name from the input field since filter names can also be crated from clicking the histogram or heatmap.

**Comment by leo-hsk** [comment]
I recently just played around with our beautiful web application and just thought about that. Is going to be fixed in sprint 5.

**Comment by antonroesler** [comment]
Nice

**Comment by antonroesler** [comment]
Seems to be fixed

**Comment by leo-hsk** [comment]
Not fixed, if generated filter names are too long
![image](https://user-images.githubusercontent.com/52975667/123218797-723dc600-d4cc-11eb-9e89-c27de7cf758c.png)

**Comment by antonroesler** [comment]
Yep, I know. Its still not working if the filter is created by clicking on histogram/heatmap

**Comment by leo-hsk** [comment]
Fixed with next pull request
