### ISSUE TITLE
Refresh views when an event happens 

### ISSUE THREAD

**Issue by antonroesler** [antonroesler/application-landscape-visualizer#128]
The **views** (graph, histogram, heatmap, coloring) should be updated when an **event** (filter, add, delete) occurs

**Comment by leo-hsk** [comment]
It is important to handle all kind of event, e.g. loading a new diagram should also refresh the statistical key figures

**Comment by antonroesler** [comment]
I'll start working on that now.

**Comment by antonroesler** [comment]
Implemented by #170
