### ISSUE TITLE
change behaviour right click on links

### ISSUE THREAD

**Issue by leo-hsk** [antonroesler/application-landscape-visualizer#129]
@b3n3m nothing happens here. is it a bug or should this feature be deleted?

**Comment by b3n3m** [comment]
makes more sense to combine this with editing function of Link data

**Comment by leo-hsk** [comment]
@b3n3m should this context menu deleted or what is the function of it?

**Comment by b3n3m** [comment]
@leo-hsk actually i use it for testing pupose, later on it makes more sense to delete it

**Comment by b3n3m** [comment]
connection type will changed by editing in infobox, rigth click not longer needed
