### ISSUE TITLE
Delete node transaction not working correctly

### ISSUE THREAD

**Issue by leo-hsk** [antonroesler/application-landscape-visualizer#131]
if a node is delete via the delete button, there is an error message
![image](https://user-images.githubusercontent.com/52975667/122748471-83988f80-d28c-11eb-9afc-790be6c790ae.png)

**Comment by b3n3m** [comment]
is this still an error on your side?... i do not see any error in cosole log

**Comment by antonroesler** [comment]
I think this was an issue caused by some kind of side effect of something else. Haven't seen this lately.
