### ISSUE TITLE
Show Parent/Child in combination with filter breaks when filter is applied by click on histogram

### ISSUE THREAD

**Issue by antonroesler** [antonroesler/application-landscape-visualizer#139]
If a filter is applied while we are in 'hide all other nodes' and than 'show parents/children' is click and a child is hidden by the filter a fail-toast appears - thats good. But if the filter was created by clicking on the diagram this doesn't work -> all children/parents are then show but the filter is still active even tough the filter should hide these nodes.

**Comment by antonroesler** [comment]
I think this is ok now.

**Comment by leo-hsk** [comment]
Fixed by @fengyilu
