### ISSUE TITLE
Changing footer information

### ISSUE THREAD

**Issue by leo-hsk** [antonroesler/application-landscape-visualizer#148]
Maybe using the github repo link, ...

**Comment by antonroesler** [comment]
<img width="846" alt="Bildschirmfoto 2021-06-29 um 16 38 30" src="https://user-images.githubusercontent.com/45258920/123817437-73218e00-d8f8-11eb-8e20-284d2a7b52f2.png">
What about that? click to get to github. @leo-hsk

**Comment by leo-hsk** [comment]
Si, may create a href on github
