### ISSUE TITLE
Property not counted the same, even though they are

### ISSUE THREAD

**Issue by leo-hsk** [antonroesler/application-landscape-visualizer#177]
Property: Department maybe tags too.
![image](https://user-images.githubusercontent.com/52975667/125086151-a1a72200-e0cb-11eb-945e-ea538f7b2320.png)
CRM is counted differently...

**Comment by leo-hsk** [comment]
You can check the situation by loading the "Basic Tutorial" diagram.

**Comment by antonroesler** [comment]
check whatsapp

**Comment by antonroesler** [comment]
This is fixed since we not longer adding spaces in front of the values
