### ISSUE TITLE
Empty AppNode can be created

### ISSUE THREAD

**Issue by antonroesler** [antonroesler/application-landscape-visualizer#43]
it is possible to create an AppNode with no name. That should not be possible, the user should be prompted an alert.

**Comment by b3n3m** [comment]
Würde ich über HTML im Browser abfangen:
_<input type="???" id="???" name="???"_ **placeholder="<Nodename>" required**>

**Comment by antonroesler** [comment]
Ja gerne so

**Comment by b3n3m** [comment]
funktioniert leider nur bei Forms:
muss über JS gelöst werden, da brauch ich Unterstützung.
https://stackoverflow.com/questions/31568776/html5-input-required-attribute-but-not-inside-form
