### ISSUE TITLE
Links should have keys.

### ISSUE THREAD

**Issue by antonroesler** [antonroesler/application-landscape-visualizer#70]
Every node gets a key which is ```Date.now()```. Links should have that too. A link only has a key attribute after it is loaded from the DB (it gets the key form MongoDB). But is a link is newly created in the diagram it doesn't have a key. Filtering these Links is then not working.

Just as with the nodes we need to add just a small line when creating nodes, someting like that:
```javascript
key = Date.now()
```

**Comment by antonroesler** [comment]
Not really necessary after all.

**Comment by b3n3m** [comment]
not longer needed for the Project
