### ISSUE TITLE
Remove gojs text in diagram

### ISSUE THREAD

**Issue by antonroesler** [antonroesler/application-landscape-visualizer#72]
The gojs default text in the upper right corner should be removed. 
<img width="254" alt="Bildschirmfoto 2021-05-31 um 08 56 52" src="https://user-images.githubusercontent.com/45258920/120152749-2611a580-c1ee-11eb-9ac4-b70609fc3141.png">

**Comment by antonroesler** [comment]
Who wants to take care of it?

**Comment by leo-hsk** [comment]
Not relevant anymore, if we create the overview on the same position
