### ISSUE TITLE
Alert when filter is deleted

### ISSUE THREAD

**Issue by antonroesler** [antonroesler/application-landscape-visualizer#88]
An alert shows up when a filter is deleted. It think it is not necessary any longer:
![Bildschirmfoto 2021-06-06 um 11 33 22](https://user-images.githubusercontent.com/45258920/120919659-02050700-c6bb-11eb-8548-562db5e28f12.png)

**Comment by leo-hsk** [comment]
Yes, it is deleted in pull request #89
