### ISSUE TITLE
Settings Menu

### ISSUE THREAD

**Issue by antonroesler** [antonroesler/application-landscape-visualizer#93]
- Form of nodes (normal [Circle, Triangle...] or our custom SVG)
- Hover modal on off
- Link Style
![Bildschirmfoto 2021-06-07 um 07 39 24](https://user-images.githubusercontent.com/45258920/120964349-7dba8e80-c763-11eb-86c3-40fc6edff7e8.png)

More Ideas in the comments...

**Comment by leo-hsk** [comment]
Settings option created. Could be extended, but should be alright for now.
