### ISSUE TITLE
Filter Menu closes if no name was specified

### ISSUE THREAD

**Issue by antonroesler** [antonroesler/application-landscape-visualizer#94]
If no name for a filter was specified an alter pops up but then the menu closes and one has to choose everything again form the start

**Comment by leo-hsk** [comment]
The reason for that is, that the closeSidenav() function is directly called after clicking on "add". So right now it does not matter if there was an error or not. Easy fixable.

**Comment by leo-hsk** [comment]
Fixed in next pull request
